### ISSUE TITLE
[Enhancement] Can you please add tutorials for nonLinear Solvers & Goal Seek

### ISSUE THREAD

**Issue by defencedog** [rafaelhlima/basic_calc_tutorial#8]
I am achemical engineer by profession & use Goal Seek & solvers on regular basis. Using these using automation will be very helpful

**Comment by rafaelhlima** [comment]
Hi, I also write solver macros quite often. Here's a sample document with a macro for the knapsack problem. You can use it as a template for your own macros.
[Bin_packing.ods](https://github.com/user-attachments/files/17006628/Bin_packing.ods)

**Comment by defencedog** [comment]
Thanks can you please refer more examples
